name: Tests

on:
  push:
    branches:
      - '**'   # run on push to every branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Solution/Flint.sln

      - name: Build
        run: dotnet build ./Tests/FlintTests/FlintTests.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./Tests/FlintTests/FlintTests.csproj --configuration Release --no-build --verbosity normal
